<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>kr</string>
		</array>
		<key>name</key>
		<string>Krypton</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#statement</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#expression</string>
			</dict>
		</array>
		<key>repository</key>
		<dict>
			<key>expression</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#comment</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#int-literal</string>
					</dict>
					<dict>
                        <key>include</key>
                        <string>#string-backtick</string>
                    </dict>
					<dict>
						<key>include</key>
						<string>#string-literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#char-literal</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#paren-expression</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#member-access-static</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#member-access</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#operator</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#type-identifier-builtin</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#statement-keyword</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#builtin-constant</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#type-identifier</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#variable</string>
					</dict>
				</array>
			</dict>
			<key>statement</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#builtin-function-call</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#statement-noop</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#block</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#expression</string>
					</dict>
				</array>
			</dict>
			<key>member-access-static</key>
            <dict>
                <key>begin</key>
                <string>(::)\s*(?!:)</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.accessor.krypton</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>(?&lt;=\S)(?=\W)|(^|(?&lt;=\s))(?=[^\\\w\s])|$</string>
                <key>patterns</key>
                <array>
                    <dict>
						<key>match</key>
						<string>\b([[:alpha:]_]\w*)\b</string>
						<key>name</key>
						<string>constant.other.class.krypton</string>
                    </dict>
                </array>
            </dict>
			<key>member-access</key>
			<dict>
				<key>begin</key>
				<string>(\.)\s*(?!\.)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.accessor.krypton</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(?&lt;=\S)(?=\W)|(^|(?&lt;=\s))(?=[^\\\w\s])|$</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b([[:alpha:]_]\w*)\b</string>
						<key>name</key>
						<string>variable.parameter.property.krypton</string>
						<key>comment</key>
						<string>should be {variable.other.property.krypton}</string>
					</dict>
				</array>
			</dict>
			<key>type-identifier</key>
			<dict>
				<key>match</key>
				<string>\b([A-Z]\w*)\b</string>
				<key>comment</key>
				<string>todo: temporary</string>
				<key>name</key>
				<string>entity.name.type.krypton</string>
			</dict>
			<key>variable</key>
			<dict>
				<key>match</key>
				<string>\b([[:alpha:]_]\w*)\b</string>
				<key>name</key>
				<string>variable.other.krypton</string>
			</dict>
			<key>builtin-function-call</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\bio\.print\b</string>
						<key>name</key>
						<string>support.function.krypton</string>
					</dict>
				</array>
			</dict>
			<key>string-literal</key>
            <dict>
                <key>name</key>
                <string>string.quoted.double.krypton</string>
                <key>begin</key>
                <string>"</string>
                <key>end</key>
                <string>"</string>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin.krypton</string>
                    </dict>
                </dict>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end.krypton</string>
                    </dict>
                </dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>constant.character.escape.krypton</string>
                        <key>match</key>
                        <string>\\["rnt\\]</string>
                    </dict>
                </array>
            </dict>
			<key>string-backtick</key>
			<dict>
				<key>name</key>
				<string>string.quoted.other.template.krypton</string>
				<key>begin</key>
				<string>`</string>
				<key>end</key>
				<string>`</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.krypton</string>
					</dict>
				</dict>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.krypton</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>name</key>
						<string>constant.character.escape.krypton</string>
						<key>match</key>
						<string>\\[`rnt\$\\]</string>
					</dict>
					<dict>
					    <key>name</key>
                        <string>meta.embedded.line.krypton</string>
                        <key>contentName</key>
                        <string>source.krypton</string>
                        <key>begin</key>
                        <string>\$\{</string>
                        <key>end</key>
                        <string>\}</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.section.embedded.begin.krypton</string>
                            </dict>
                        </dict>
                        <key>endCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.section.embedded.end.krypton</string>
                            </dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>source.krypton</string>
                            </dict>
                        </dict>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#expression</string>
                            </dict>
                        </array>
					</dict>
				</array>
			</dict>
			<key>char-literal</key>
			<dict>
				<key>name</key>
				<string>string.quoted.single.krypton</string>
				<key>begin</key>
				<string>'</string>
				<key>end</key>
				<string>'</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.krypton</string>
					</dict>
				</dict>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.krypton</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>name</key>
						<string>constant.character.escape.krypton</string>
						<key>match</key>
						<string>\\['rnt\\]</string>
					</dict>
				</array>
			</dict>
			<key>builtin-constant</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>name</key>
						<string>constant.language.krypton</string>
						<key>match</key>
						<string>\b(true|false|null)\b</string>
					</dict>
				</array>
			</dict>
			<key>type-identifier-builtin</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>name</key>
						<string>entity.name.type.alias.krypton</string>
						<key>comment</key>
						<string>+should be {storage.type.krypton}</string>
						<key>match</key>
						<string>\b(array|bool|int|int32|string|object|char)\b</string>
					</dict>
					<dict>
						<key>name</key>
						<string>entity.name.type.builtin.krypton</string>
						<key>comment</key>
						<string>+should be {storage.type.class.builtin.krypton}</string>
						<key>match</key>
						<string>\b(Array|Bool|Int32|Function|Map|Set|Ref|Opt|Object|String|Enumerable|void)\b</string>
					</dict>
				</array>
			</dict>
			<key>statement-keyword</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>name</key>
						<string>keyword.control.krypton</string>
						<key>match</key>
						<string>\b(ret|func|if|else|for|while|repeat|switch|case|break|continue|class|interface|enum|type|pub|inline|struct|extends|implements|try|catch|finally|throw|self|mut|ref|let|const|use|operator|as|import|export|from)\b</string>
					</dict>
					<dict>
						<key>name</key>
						<string>variable.parameter.krypton</string>
						<key>comment</key>
						<string>should be something else {keyword.operator.krypton}?</string>
						<key>match</key>
						<string>\b(new|instanceof|in)\b</string>
					</dict>
					<dict>
						<key>name</key>
						<string>variable.language.krypton</string>
						<key>match</key>
						<string>\b(this)\b</string>
					</dict>
				</array>
			</dict>
			<key>statement-noop</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\;$</string>
						<key>name</key>
						<string>punctuation.terminator.statement.krypton</string>
					</dict>
				</array>
			</dict>
			<key>block</key>
			<dict>
				<key>name</key>
				<string>meta.block.krypton</string>
				<key>begin</key>
				<string>\{</string>
				<key>end</key>
				<string>\}</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.scope.begin.krypton</string>
					</dict>
				</dict>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.scope.end.krypton</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#statement</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#expression</string>
					</dict>
				</array>
			</dict>
			<key>paren-expression</key>
			<dict>
				<key>name</key>
				<string>meta.parens.krypton</string>
				<key>begin</key>
				<string>\(</string>
				<key>end</key>
				<string>\)</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.parenthesis.begin.krypton</string>
					</dict>
				</dict>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.parenthesis.end.krypton</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#expression</string>
					</dict>
				</array>
			</dict>
			<key>comment</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>name</key>
						<string>comment.block.krypton</string>
						<key>begin</key>
						<string>/\*</string>
						<key>end</key>
						<string>\*/</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.comment.begin.krypton</string>
							</dict>
						</dict>
						<key>endCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.comment.end.krypton</string>
							</dict>
						</dict>
					</dict>
					<dict>
						<key>name</key>
						<string>comment.line.number-sign.krypton</string>
						<key>begin</key>
						<string>//</string>
						<key>end</key>
						<string>$</string>
						<key>beginCaptures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.comment.krypton</string>
							</dict>
						</dict>
					</dict>
				</array>
			</dict>
			<key>int-literal</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>name</key>
						<string>constant.numeric.hex.krypton</string>
						<key>match</key>
						<string>\b0x\[0-9a-fA-F]+\b</string>
					</dict>
					<dict>
						<key>name</key>
						<string>constant.numeric.binary.krypton</string>
						<key>match</key>
						<string>\b0b[01]+\b</string>
					</dict>
					<dict>
						<key>name</key>
						<string>constant.numeric.krypton</string>
						<key>match</key>
						<string>\b[+-]?[0-9]+\b</string>
					</dict>
				</array>
			</dict>
			<key>operator</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>name</key>
						<string>keyword.operator.assignment.compound.krypton</string>
						<key>match</key>
						<string>\+=|\-=|\*=|%=|/=</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.operator.assignment.compound.bitwise.krypton</string>
						<key>match</key>
						<string>\^=|&lt;&lt;=|&gt;&gt;=</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.operator.comparison.krypton</string>
						<key>match</key>
						<string>!=|==|&lt;=|&gt;=|&lt;|&gt;</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.operator.logical.krypton</string>
						<key>match</key>
						<string>!|\|\|</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.operator.bitwise.krypton</string>
						<key>match</key>
						<string>&amp;|\||\^|~</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.operator.arithmetic.krypton</string>
						<key>match</key>
						<string>\+|\-|\*\*?|/|%</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.operator.spread.krypton</string>
						<key>match</key>
						<string>\.\.\.</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.operator.range.krypton</string>
						<key>match</key>
						<string>\.\.=?</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.operator.decrement.krypton</string>
						<key>match</key>
						<string>\-\-</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.operator.increment.krypton</string>
						<key>match</key>
						<string>\+\+</string>
					</dict>
					<dict>
						<key>name</key>
						<string>keyword.operator.assignment.krypton</string>
						<key>match</key>
						<string>=</string>
					</dict>
				</array>
			</dict>
		</dict>
		<key>scopeName</key>
		<string>source.krypton</string>
		<key>foldingStartMarker</key>
		<string>\{</string>
		<key>foldingStopMarker</key>
		<string>\}</string>
	</dict>
</plist>
